language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

sudo: false

services:
  - elasticsearch

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.1.0.deb && sudo dpkg -i --force-confnew elasticsearch-6.1.0.deb && sudo service elasticsearch restart
  - pip install flake8
  - pip install coveralls
  - pip install -r "requirements.txt"

before_script:
  - sleep 20

script:
  - flake8 .
  - cd tests
  - coverage run --source=citadel run_tests.py

after_success:
  - coveralls
